#!/usr/bin/env bash

set -ex

if ! git diff-index --quiet HEAD --; then
    echo "You must have a clean working copy before building" >&2
    exit 1
fi

git co -B release

npm install
npm run build

git add -f dist
git commit -m 'Release files'
git push -fu origin release:release

git co -
